//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryConverterUI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBinaryConverterService")]
    public interface IBinaryConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBinaryConverterService/GetBinary", ReplyAction="http://tempuri.org/IBinaryConverterService/GetBinaryResponse")]
        string GetBinary(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBinaryConverterService/GetBinary", ReplyAction="http://tempuri.org/IBinaryConverterService/GetBinaryResponse")]
        System.Threading.Tasks.Task<string> GetBinaryAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBinaryConverterService/GetOneCount", ReplyAction="http://tempuri.org/IBinaryConverterService/GetOneCountResponse")]
        int GetOneCount(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBinaryConverterService/GetOneCount", ReplyAction="http://tempuri.org/IBinaryConverterService/GetOneCountResponse")]
        System.Threading.Tasks.Task<int> GetOneCountAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBinaryConverterServiceChannel : BinaryConverterUI.ServiceReference1.IBinaryConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BinaryConverterServiceClient : System.ServiceModel.ClientBase<BinaryConverterUI.ServiceReference1.IBinaryConverterService>, BinaryConverterUI.ServiceReference1.IBinaryConverterService {
        
        public BinaryConverterServiceClient() {
        }
        
        public BinaryConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BinaryConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BinaryConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BinaryConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBinary(int value) {
            return base.Channel.GetBinary(value);
        }
        
        public System.Threading.Tasks.Task<string> GetBinaryAsync(int value) {
            return base.Channel.GetBinaryAsync(value);
        }
        
        public int GetOneCount(int value) {
            return base.Channel.GetOneCount(value);
        }
        
        public System.Threading.Tasks.Task<int> GetOneCountAsync(int value) {
            return base.Channel.GetOneCountAsync(value);
        }
    }
}
